#!/bin/sh
# tbd - Start/Stop thebridge Radio-Over-IP software
# by VE7LTD - Nov 29, 2012

### BEGIN INIT INFO
# Provides:          tbd
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Should-Start:      
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts/Stops thebridge daemon
### END INIT INFO

set -e

TBD="/usr/sbin/tbd"
OPTIONS="-s"

# Check for daemon presence
[ -x "$TBD" ] || exit 0

# Get lsb functions
. /lib/lsb/init-functions

case "$1" in
  start)
    log_begin_msg "Starting thebridge ... "
    start-stop-daemon --start --quiet --oknodo --exec "$TBD" -- "$OPTIONS"
    log_end_msg $?
    ;;
  stop)
    log_begin_msg "Stopping thebridge ... "
    start-stop-daemon --stop --quiet --oknodo --retry 2 --exec "$TBD" -- "$OPTIONS"
    log_end_msg $?
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  reload|force-reload) 
    log_begin_msg "Reloading tbd.conf ... "
    start-stop-daemon --stop --signal HUP --exec "$TBD"
    log_end_msg $?
    ;;
  status)
    status_of_proc "$TBD" tbd
    ;;
  *)
    log_success_msg "Usage: /etc/init.d/tbd {start|stop|restart|reload|force-reload|status}"
    exit 1
esac
