#!/bin/sh
#
# description: remove thebridge startup scripts on Debian Linux (LSB System)
# $Id: uninstall,v 1.1 2012/12/10 06:00:13 wb6ymh Exp $

set -x
update-rc.d -f tbd remove
rm /usr/sbin/tbd
rm /etc/rc.d/init.d/tbd
cd ..
make uninstall
cd Debian
