#!/bin/sh
#
# description: install thebridge startup scripts on RedHat Linux (System V like)
# $Id: install,v 1.2 2004/11/29 15:27:05 wb6ymh Exp $

set -x
cd ..
make install
cd RedHat
ln -s /usr/local/libexec/tbd /usr/sbin
if [ ! -d /etc/rc.d/init.d ]; then
   echo 'creating /etc/rc.d/init.d'
   mkdir /etc/rc.d/init.d
fi
cp tbd /etc/rc.d/init.d
ln -s /etc/rc.d/init.d/tbd /etc/rc.d/rc0.d/K73tbd
ln -s /etc/rc.d/init.d/tbd /etc/rc.d/rc1.d/K73tbd
ln -s /etc/rc.d/init.d/tbd /etc/rc.d/rc2.d/S73tbd
ln -s /etc/rc.d/init.d/tbd /etc/rc.d/rc3.d/S73tbd
ln -s /etc/rc.d/init.d/tbd /etc/rc.d/rc4.d/S73tbd
ln -s /etc/rc.d/init.d/tbd /etc/rc.d/rc5.d/S73tbd
ln -s /etc/rc.d/init.d/tbd /etc/rc.d/rc6.d/K73tbd

