#!/bin/sh
#
# description: remove thebridge startup scripts on RedHat Linux (System V like)
# $Id: uninstall,v 1.1.1.1 2002/08/10 20:33:41 wb6ymh Exp $

set -x
rm /usr/sbin/tbd
rm /etc/rc.d/init.d/tbd
rm /etc/rc.d/rc0.d/K73tbd
rm /etc/rc.d/rc1.d/K73tbd
rm /etc/rc.d/rc2.d/S73tbd
rm /etc/rc.d/rc3.d/S73tbd
rm /etc/rc.d/rc4.d/S73tbd
rm /etc/rc.d/rc5.d/S73tbd
rm /etc/rc.d/rc6.d/K73tbd
cd ..
make uninstall
cd RedHat

